language: cpp

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc swig texinfo iverilog itcl3

script:
  - ./bootstrap
  - ./configure --enable-python --enable-tcl --enable-verilog
  - make
  - cd regress
  - ./regress.py
  - ./regress.py -d atmega2560
  - make -C gtest check-local
  - make -C avrtest avrtest
  - make -C extinttest extinttest
  - make -C modtest modtest
  - make -C timertest timertest
  - make -C verilog verilogtest
  - make -C tcl docheck

